#![no_std]
#![no_main]

// use smart_leds::{SmartLedsWrite, RGB8};
// use ws2812_esp32_rmt_driver::Ws2812Esp32RmtDriver;
// use rmk::channel::{CONTROLLER_CHANNEL, ControllerSub};
// use rmk::controller::Controller;
// use rmk::event::ControllerEvent;
use rmk::macros::rmk_keyboard;

// pub struct Ws2812LayerController {
//     ws: Ws2812Esp32RmtDriver<'static>,
//     sub: ControllerSub,
// }

// impl Ws2812LayerController {
//     pub fn new(ws: Ws2812Esp32RmtDriver<'static>) -> Self {
//         Self {
//             ws,
//             sub: unwrap!(CONTROLLER_CHANNEL.subscriber()),
//         }
//     }

//     fn layer_color(layer: u8) -> RGB8 {
//         match layer {
//             0 => RGB8 { r: 0,   g: 255, b: 0   }, // green
//             1 => RGB8 { r: 0,   g: 0,   b: 255 }, // blue
//             2 => RGB8 { r: 255, g: 0,   b: 0   }, // red
//             3 => RGB8 { r: 255, g: 165, b: 0   }, // orange
//             _ => RGB8 { r: 64,  g: 0,   b: 128 }, // purple
//         }
//     }
// }

// impl Controller for Ws2812LayerController {
//     type Event = ControllerEvent;

//     async fn process_event(&mut self, event: Self::Event) {
//         if let ControllerEvent::Layer(layer) = event {
//             let color = Self::layer_color(layer as u8);
//             let _ = self.ws.write([color].iter().cloned());
//         }
//     }

//     async fn next_message(&mut self) -> Self::Event {
//         self.sub.next_message_pure().await
//     }
// }

// Vial config is automatically generated by `build.rs`, according to `vial.json`
// Please put `vial.json` at your project's root
#[rmk_keyboard]
mod keyboard {

    // #[controller(event)]
        // fn ws2812_layer_led() -> Ws2812LayerController {
            // let ws = Ws2812Esp32RmtDriver::new(0, 33).unwrap();
            // Ws2812LayerController::new(ws)
            //    }
}
